version: 2
jobs:
    # build_master:
    #     docker:
    #         - image: circleci/node:10.13.0
    #     steps:
    #         - checkout
    #         - run:
    #             name: Install dependencies
    #             command: |
    #               npm install
    #               sudo apt-get update && sudo apt-get install -y python-dev
    #               curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
    #               sudo python get-pip.py
    #               sudo pip install awsebcli --upgrade
    #         - run:
    #             name: Building...
    #             command: npm run build
    #         - run:
    #             name: Adding to git
    #             command: git add .
    #         - run:
    #             name: Init beanstalk
    #             command: eb init $APPLICATION -r $AWS_REGION -p $APPLICATION_PLATFORM
    #         - run:
    #             name: Deploying
    #             command: eb deploy --staged $ENVIRONMENT_PROD
    test_dev:  
        steps:
            - run:
                name: Test
                command: |
                  npm run test
workflows:
    version: 2
    build_master:
        jobs:
            - build_master:
                filters:
                    branches:
                        only: master
    test_dev:
        jobs:
            - test_dev:
                filters:
                    branches:
                        only: dev