version: 2
jobs:
    build_master:
        docker:
            - image: circleci/node:14.16.0
        steps:
            - checkout
            - run:
                name: Install npm dependencies
                command: |
                  npm i
                  sudo python get-pip.py
                  sudo pip install awsebcli --upgrade
            - run:
                name: Test
                command: |
                  npm run test
    test_dev:  
        docker:
            - image: circleci/node:14.16.0
        steps:
            - checkout
            - run:
                name: Install npm dependencies
                command: |
                  npm i
            - run:
                name: Test
                command: |
                  npm run test
            - store_artifacts:
                path: ./test-results/junit
            - store_test_results:
                path: ./test_result/
workflows:
    version: 2
    build_master:
        jobs:
            - build_master:
                filters:
                    branches:
                        only: master
    test_dev:
        jobs:
            - test_dev:
                filters:
                    branches:
                        only: dev