version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.2
jobs:
    build_master:
        docker:
            - image: cimg/node:15.14.0
        steps:
            - checkout
            # - run:
            #     command: |
            #         sudo apt-get -y -qq update
            #         sudo apt-get install python-pip python-dev build-essential
            - eb/setup
            - run:
                name: Install npm dependencies
                command: |
                  npm i
            - run:
                name: Test
                command: |
                  npm run test
            - store_artifacts:
                path: ./test-results/junit
            - store_test_results:
                path: ./test_result/
            - run: 
                name: EB Deploy
                command: |
                    eb deploy Testeimed-env
                    eb status
    test_dev:  
        docker:
            - image: cimg/node:15.14.0
        steps:
            - checkout
            - run:
                name: Install npm dependencies
                command: |
                  npm i
            - run:
                name: Test
                command: |
                  npm run test
            - store_artifacts:
                path: ./test-results/junit
            - store_test_results:
                path: ./test_result/
workflows:
    version: 2
    build_master:
        jobs:
            - build_master:
                filters:
                    branches:
                        only: master
    test_dev:
        jobs:
            - test_dev:
                filters:
                    branches:
                        only: dev