version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.2
jobs:
    build_master:
        docker:
            - image: cimg/node:15.14.0
        steps:
            - checkout
            - run:
                name: Install npm dependencies
                command: |
                  npm i
            - run:
                name: Test
                command: |
                  npm run test
            - store_artifacts:
                path: ./test-results/junit
            - store_test_results:
                path: ./test_result/
            - eb/setup
            - run: 
                name: EB Deploy
                command: |
                    eb init $APPLICATION_NAME -r $AWS_DEFAULT_REGION -p node.js
                    eb deploy -l $CIRCLE_BUILD_NUM $ENVIROMENT
                    eb status
    test_dev:  
        docker:
            - image: cimg/node:15.14.0
        steps:
            - checkout
            - run:
                name: Install npm dependencies
                command: |
                  npm i
            - run:
                name: Test
                command: |
                  npm run test
            - store_artifacts:
                path: ./test-results/junit
            - store_test_results:
                path: ./test_result/
            - run:
                command: npm run build
            - run:
                name: Create a Zip file
                command: zip build.zip -r build public package.json
            - persist_to_workspace:
                root: .
                paths:
                    - build.zip
            - store_artifacts:
                path: build.zip
workflows:
    version: 2.1
    build_master:
        jobs:
            - build_master:
                filters:
                    branches:
                        only: master
    test_dev:
        jobs:
            - test_dev:
                filters:
                    branches:
                        only: dev