version: 2
jobs:
    build_master:
        steps:
            - run:
                name: Test
                command: |
                  npm run test
    test_dev:  
        steps:
            - run:
                name: Test
                command: |
                  npm run test
workflows:
    version: 2
    build_master:
        jobs:
            - build_master:
                filters:
                    branches:
                        only: master
    test_dev:
        jobs:
            - test_dev:
                filters:
                    branches:
                        only: dev